### ISSUE TITLE
New Product page layout errors

### ISSUE THREAD

**Issue by oksushi** [freakdesign/shopify-custom-fields#11]
Shopify have just launched a new Product screen inside the admin, and it breaks the Custom Field tool:

`Custom Fields error : setup_custom_fields() : target html not found`

Screenshot:
![screenshot 2015-03-11 09 32 53](https://cloud.githubusercontent.com/assets/466722/6586880/b7a65ee6-c7d1-11e4-8e39-e9dd58f2345c.png)

I don’t know how widespread the new Product screen layout is yet

**Comment by freakdesign** [comment]
The fix for this has been ready to go for a while/

As of yesterday 5% of current users and 10% of new shops got the new layout. Don't expect it to be long before all get it. Once the rollout is complete I'll push a new update here, and to the main CDN. I know plenty of people still grab and use the files directly from here (rather than the CDN) so I've got to be a bit careful on when I update it.

If you're super stuck you can use the bookmarklet at the link below, but don't expect that link to work for long. ('ll pull it as soon as the main version is pushed).

https://freakdesign-us.s3.amazonaws.com/shopify/shopifyFD/beta/installation.html

**Comment by freakdesign** [comment]
Looks like the rollout is now beyond 50% so I'll push an update to git shortly, with the cdn to be updated at the end of the day.
