### ISSUE TITLE
Not visible in Settings

### ISSUE THREAD

**Issue by metaxy** [freakdesign/shopify-custom-fields#52]
I installed the plugin. But when i try the set some meatfield in `admin/settings/general` it wont't show any UI.
I does load the script and calls the api (successfully)
![screenshot_20171117_113152](https://user-images.githubusercontent.com/82704/32942974-ed56bf80-cb8a-11e7-88ef-c6bc56e52eab.png)

**Comment by freakdesign** [comment]
This seems related: https://github.com/freakdesign/shopify-custom-fields/issues/33

To reiterate, the Custom Fields extension doesn't add UI in `admin/settings/general`. You'll need to use other tools to create the setup metafields. Since more people are wanting to manage them all in the one tool The next full release version (so not minor update) of Custom Fields will have it built in.
